@extends('front.layouts.base')
@section('title')
Cookie Policy | Sojournplanet Luxury Tailor-Made Travel
@endsection
@section('meta_title2')
Cookie Policy | Sojournplanet Luxury Tailor-Made Travel
@endsection
@section('meta_description2')
Understand how Sojournplanet uses cookies to enhance your luxury travel experience. Learn about data collection, cookie types, and how to manage your preferences. Explore our full cookie policy here.

@endsection
@section('content')
<div class="container-fluid d-flex  justify-content-center align-items-center p-2"
    style="background-image:linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url({{ asset('img/bosque.jpg') }});background-size:cover; height:250px;background-position:center;">
    <h1 class="patua text-center text-white fs-4">Cookie Policy</h1>

</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto mt-5 mb-5">
            <p class="open texto">Our website, like many others, utilizes cookies. These tiny data files are placed on
                your computer, mobile device, or
                browser during your visit to a website. They provide us with insights into your interactions with our
                site, which aids
                in its operation and enhancement by collecting data.</p>
            <p class="open texto">This page contains our cookie statement. It outlines the various types of cookies (and
                related technologies) we employ,
                the reasons for their use, and clarifies your rights regarding the management of these cookies.</p>
            <p class="open texto">Occasionally, we might use cookies and similar technologies to gather personal
                information, or information that could
                eventually be considered personal. For more detailed information on how we handle your personal data,
                please refer to
                our privacy policy.</p>
            <h2 class="patua fs-4 mt-4">Which cookies do we use?</h2>
            <p class="open texto">We employ two types of cookies on our website: 'first-party cookies' and 'third-party
                cookies.' First-party cookies are
                those that we set ourselves, and we use the data collected and generated by these cookies for our own
                specific purposes.
                Third-party cookies, on the other hand, are placed by external websites that have features linked to our
                website, such
                as social media platforms whose sharing buttons we might include (like Facebook, YouTube, Instagram, and
                X). These
                third-party entities have the ability to recognize your computer or device not only when you visit our
                site but also as
                you browse other parts of the internet.</p>
            <h2 class="patua fs-4 mt-4">Why do we use cookies?</h2>
            <p class="open texto">We utilize both first-party and third-party cookies for a variety of reasons.</p>
            <p class="open texto">First and foremost, certain cookies are essential for the functioning of our website;
                these are known as ‘essential’ or
                ‘strictly necessary’ cookies. Additionally, we use other types of cookies to enhance our understanding
                of your
                preferences during your visits. These are referred to as ‘performance’ or ‘functionality’ cookies. For
                instance, they
                help us tailor content to better match your interests when you navigate our site.</p>
            <p class="open texto">Moreover, we sometimes permit third parties to place cookies on our website for
                various purposes, such as advertising or
                information collection. More detailed explanations of these practices are provided further on.</p>
            <h2 class="patua fs-4 mt-4">Types of Cookies We Use and Their Functions</h2>
            <h3 class="patua fs-5 mt-4">1-Strictly Necessary Cookies:</h3>
            <p class="open texto">These cookies are essential for the operation of our website and cannot be turned off.
                They are typically set in
                response to actions made by you, such as setting your privacy preferences, logging in, or filling out
                forms. These
                cookies do not store any personally identifiable information.</p>
            <p class="open texto">If you choose to block these cookies through your browser settings, it could affect
                the functionality of our site.</p>
            <h3 class="patua fs-5 mt-4">2-Performance Cookies:</h3>
            <p class="open texto">These cookies help us understand how visitors interact with our website by collecting
                information about the areas
                visited, the time spent on the site, and any issues encountered, such as error messages. This helps us
                improve the
                performance of our website, making it more user-friendly by enabling us to monitor usage and optimize
                the site
                accordingly.</p>
            <p class="open texto">The data collected by these cookies is aggregated and anonymous, which means we cannot
                identify you personally from this
                information. Disabling these cookies means we won’t be able to learn from your visit, thereby hindering
                our ability to
                improve your user experience in the future.</p>
            <p class="open texto">For instance, we use Google Analytics to provide insights into how our site is used.
                More information on how Google
                Analytics handles user data can be found here: <a
                    href="https://support.google.com/analytics/answer/6004245?hl=en" target="_blank"
                    rel="noopener noreferrer">Google Analytics</a> </p>
            <h2 class="patua fs-4 mt-4">Functional Cookies:</h2>
            <p class="open texto">Functional cookies allow our website to remember choices you make (such as your user
                name, language, or the region you
                are in) and provide enhanced, more personal features. They may be set by us or by third-party providers
                whose services
                we have added to our pages.</p>
            <p class="open texto">These cookies can also be used to remember changes you have made to text size, fonts,
                and other parts of web pages that
                you can customize. They are also used to provide services you have asked for, such as watching a video
                or commenting on
                a blog. The information these cookies collect may be anonymized, and they cannot track your browsing
                activity on other
                websites.</p>
            <p class="open texto">If you do not allow these cookies, then some or all of these services may not function
                properly.</p>
            <h2 class="patua fs-4 mt-4">Targeting Cookies:</h2>
            <p class="open texto">Our advertising partners may use targeting cookies to develop a profile of your
                interests and display relevant
                advertisements on other sites you visit across the internet. These cookies do not store personal
                information directly
                but identify your browser and internet device. If you choose not to allow these cookies, you will still
                see ads, but
                they may be less relevant to your interests.</p>
            <p class="open texto">For instance, our website includes targeting cookies from Facebook, which are used to
                gather information for advertising
                purposes.</p>
            <h2 class="patua fs-4 mt-4">How Can I Control Cookies?</h2>
            <p class="open texto">You have the ability to accept or reject cookies, and you can control cookies through
                your web browser settings. The
                process for managing cookie preferences varies by browser, but you can typically find instructions in
                the help menu of
                your browser:</p>
            <p class="open texto"><span class="fw-bold">-Edge: </span> Manage cookies in Microsoft Edge Delete cookies
                in Microsoft Edge</p>
            <p class="open texto"><span class="fw-bold">-Chrome:</span> Manage cookies in Google Chrome Delete cookies
                in Google Chrome</p>
            <p class="open texto"><span class="fw-bold">-Firefox:</span> Manage cookies in Mozilla Firefox Delete
                cookies in Mozilla Firefox</p>
            <p class="open texto">If you reject all cookies, be aware that certain features of our website may not
                function as intended.</p>
            <p class="open texto">To prevent Google Analytics from tracking you across all websites, visit: <a
                    href="https://support.google.com/analytics/answer/181881?hl=en" target="_blank"
                    rel="noopener noreferrer">Google Analytics</a> </p>
            <h2 class="patua fs-4 mt-4">More Information:</h2>
            <p class="open texto">For further details or questions regarding our cookie use, please contact us at <a
                    href="mailto:dataprotection@sojournplanet.com">dataprotection@sojournplanet.com</a>. We are
                committed to providing clarity on our use of cookies and ensuring your browsing preferences are
                respected.</p>


        </div>
    </div>
</div>

@endsection